# Generated by Django 4.2.25 on 2025-11-03 18:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Templates',
            fields=[
                ('template_id', models.AutoField(primary_key=True, serialize=False)),
                ('template_name', models.CharField(max_length=128)),
                ('template_category', models.CharField(max_length=128)),
                ('template_content', models.TextField()),
                ('template_params', models.JSONField()),
                ('template_status', models.CharField(max_length=32)),
                ('is_active', models.BooleanField()),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('user_id', models.AutoField(primary_key=True, serialize=False)),
                ('username', models.CharField(max_length=64)),
                ('email', models.EmailField(max_length=128)),
                ('password', models.CharField(max_length=255)),
                ('role', models.CharField(choices=[('Admin', 'Admin'), ('User', 'User')], max_length=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('is_active', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='Workflow',
            fields=[
                ('workflow_id', models.AutoField(primary_key=True, serialize=False)),
                ('workflow_name', models.CharField(max_length=128)),
                ('status', models.CharField(choices=[('Active', 'Active'), ('Pending', 'Pending'), ('Rejected', 'Rejected')], max_length=10)),
                ('root_template_id', models.IntegerField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='workflows', to='backend.user')),
            ],
        ),
        migrations.CreateModel(
            name='WorkflowMapping',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_root', models.BooleanField(default=False)),
                ('template_sequence_order', models.IntegerField()),
                ('condition_trigger', models.CharField(max_length=255)),
                ('template_params', models.JSONField()),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True)),
                ('template', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='backend.templates')),
                ('workflow', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='mapping', to='backend.workflow')),
            ],
        ),
        migrations.AddField(
            model_name='templates',
            name='workflow',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='templates', to='backend.workflow'),
        ),
        migrations.CreateModel(
            name='APILog',
            fields=[
                ('log_id', models.AutoField(primary_key=True, serialize=False)),
                ('request_payload', models.JSONField()),
                ('response_code', models.IntegerField()),
                ('response_message', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('node_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='backend.workflowmapping')),
                ('template', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='backend.templates')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='logs', to='backend.user')),
                ('workflow', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='logs', to='backend.workflow')),
            ],
        ),
    ]
