# Generated by Django 4.2.25 on 2025-11-17 17:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='workflowmapping',
            name='parent_mapping',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='child_mappings', to='backend.workflowmapping'),
        ),
        migrations.AlterField(
            model_name='workflowmapping',
            name='condition_trigger',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
        migrations.AlterField(
            model_name='workflowmapping',
            name='template_params',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='workflowmapping',
            name='workflow',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='mappings', to='backend.workflow'),
        ),
    ]
