# Generated by Django 4.2.25 on 2025-12-15 14:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0002_workflowmapping_parent_mapping_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='templates',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
    ]
