# Generated by Django 4.2.25 on 2025-12-15 21:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0003_alter_templates_is_active'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='workflow',
            name='created_by',
        ),
    ]
