# Generated by Django 4.2.25 on 2025-12-16 20:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0004_remove_workflow_created_by'),
    ]

    operations = [
        migrations.AlterField(
            model_name='workflow',
            name='workflow_name',
            field=models.CharField(max_length=128, unique=True),
        ),
    ]
