# Generated by Django 4.2.25 on 2025-12-22 23:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0005_alter_workflow_workflow_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='apilog',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='logs', to='backend.user'),
        ),
    ]
